title: CV | Ade Mahmud
description:  Ade Mahmud's CV.
url: https://ademahmudf.github.io
baseurl: '/cv'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
